<?xml version="1.0"?>
<robot name="robot_firas" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_lenth" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_heigh" value="0.02" />
    <xacro:property name="arm_cylindre_radius" value="0.02" />
    <xacro:property name="arm_cylindre_lenght" value="0.3" />

    <link name="arm_base_link">
        
        <visual>
            
            <geometry>
                <box size="${arm_base_lenth} ${arm_base_width} ${arm_base_heigh}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${arm_base_heigh}" rpy="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_lenth} ${arm_base_width} ${arm_base_heigh}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${arm_base_heigh}" rpy="0.0 0.0 0.0"/>
            
        </collision>
        <xacro:box_inertia m="0.5"  l="${2*arm_base_lenth}" w="${2*arm_base_width}" h="${2*arm_base_heigh}"
                           xyz="0.0 0.0 ${arm_base_heigh}"  rpy="0.0 0.0 0.0"/>
    
    </link>
    <link name="forearm_link">
        
        <visual>
            
            <geometry>
                <cylinder radius="0.02" length="0.3"/>
            </geometry>
            <material name="orange"/>
            <origin xyz="0.0 0.0 ${arm_cylindre_lenght/2}" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                    <cylinder radius="0.02" length="0.3"/>
                </geometry>
                
                <origin xyz="0.0 0.0 ${arm_cylindre_lenght/2}" rpy="0.0 0.0 0.0"/>
            
        </collision>
        <xacro:wheel_inertia m="0.3"  r="${2*arm_cylindre_radius}" h="${2*arm_cylindre_lenght}"
                             xyz="0.0 0.0 ${arm_cylindre_lenght/2}"  rpy="0.0 0.0 0.0"/>  
    
    </link>
    <link name="hand_link">
        
        <visual>
            
            <geometry>
                <cylinder radius="0.02" length="0.3"/>
            </geometry>
            <material name="orange"/>
            <origin xyz="0.0 0.0 ${arm_cylindre_lenght/2}" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.02" length="0.3"/>
            </geometry>
            <origin xyz="0.0 0.0 ${arm_cylindre_lenght/2}" rpy="0.0 0.0 0.0"/>
            
        </collision>
        <xacro:wheel_inertia m="0.3"  r="${2*arm_cylindre_radius}" h="${2*arm_cylindre_lenght}"
                             xyz="0.0 0.0 ${arm_cylindre_lenght/2}"  rpy="0.0 0.0 0.0"/>  
    
    </link>

    <joint name="base_arm_joint" type="revolute">
        <origin xyz="0.0 0.0 ${arm_base_heigh}" rpy="0.0 0.0 0.0"/>
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="${pi/2}" effort="100.0" velocity="100.0"/>
        <dynamics friction="0.05" damping="0.1" />
        
    </joint>

    <joint name="hand_arm_joint" type="revolute">
        <origin xyz="0.0 0.0 ${arm_cylindre_lenght}" rpy="0.0 0.0 0.0"/>
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="${pi/2}" effort="100.0" velocity="100.0"/>
        <dynamics friction="0.05" damping="0.1" />
        
    </joint>

</robot>