<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="base_lenth" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_heigh" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_heigh" value="0.05" />
    <xacro:property name="caster_wheel_radius" value="0.05" />
    

    <link name="base_footprint">   
    </link>

    <link name="base_link">
        <visual>
                <geometry>
                    <box size=" ${base_lenth} ${base_width} ${base_heigh}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
                <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                    <box size=" ${base_lenth} ${base_width} ${base_heigh}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
            
        </collision>
        <xacro:box_inertia m="5.0"  l="${2*base_lenth}" w="${2*base_width}" h="${2*base_heigh}"
                           xyz="0.0 0.0 0.1"  rpy="0.0 0.0 0.0"/>
        
                           
    </link>
    
    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <origin xyz="0.0 0.0 0.025" rpy="0.0 0.0 0.0"/>
            <material name="red"/>
        </visual>
        
    </link>
    <link name="box_link">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <origin xyz="0.0 0.0 0.025" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
    </link>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <material name="grey"/>
            <origin xyz="0.0 -0.0225 0" rpy="${pi/2.0} 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <origin xyz="0.0 -0.0225 0" rpy="${pi/2.0} 0.0 0.0"/>
            
        </collision>
        
        <xacro:wheel_inertia m="1.0"  r="${2*wheel_radius}" h="${2*wheel_heigh}"
                             xyz="0.0 -0.0225 0"  rpy="${pi/2.0} 0.0 0.0"/>  
    </link>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <material name="grey"/>
            <origin xyz="0.0 0.0225 0" rpy="${pi/2.0} 0.0 0.0"/>
        </visual> 
        <collision>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <origin xyz="0.0 0.0225 0" rpy="${pi/2.0} 0.0 0.0"/>
            
        </collision>
        
        <xacro:wheel_inertia m="1.0"  r="${2*wheel_radius}" h="${2*wheel_heigh}"
                             xyz="0.0  0.0225 0"  rpy="${pi/2.0} 0.0 0.0"/>      
    </link>

    
    <link name="caster_link">
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <material name="grey"/>
            <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0"/>
        </visual>  
        <collision>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0"/>
            
        </collision>
        
        <xacro:sphere_inertia m="0.5"  r="${2*caster_wheel_radius}" 
                             xyz="0.0 0.0 0"  rpy="0.0 0.0 0.0"/>  
                                  
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
        
    </joint>

    <joint name="base_lidar" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.0 0.0 0.2" rpy="0.0 0.0 0.0"/>
        
    </joint>
    <joint name="lidar_box" type="fixed">
        <parent link="lidar_link"/>
        <child link="box_link"/>
        <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
        
    </joint>
    <joint name="base_right_wheel" type="continuous">
        <origin xyz="${-base_lenth/4.0} -0.2 0.0" rpy="0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>
    <joint name="base_left_wheel" type="continuous">
        <origin xyz="${-base_lenth/4.0} 0.2 0.0" rpy="0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>
    
    <joint name="caster_link" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link"/>
        <origin xyz="0.15 0.0 -0.05" rpy="0.0 0.0 0.0"/>
        
    </joint>

</robot>   
    
