<?xml version="1.0"?>
<robot name="robot_firas" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="common_urdf.xacro"/>
    <xacro:include filename="mobile_base.xacro"/>   
    <xacro:include filename="mobile_base_gazebo.xacro"/>  
    <xacro:include filename="camera.xacro"/> 
    <xacro:include filename="arm.xacro"/> 
    <xacro:include filename="arm_gazebo.xacro"/> 

    <joint name="arm_robot" type="revolute">
        <origin xyz="${(base_lenth/2)- 0.05} 0.0 ${base_heigh}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="0.0" velocity="0.0"/>
    </joint>
    

</robot>
